import { ClerkProvider as Provider } from "@clerk/nextjs";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang='en'>
        <body>{children}</body>
      </html>
    </Provider>
  );
}
