import { Inter } from "next/font/google";
import { ClerkProvider as Provider } from "@clerk/nextjs";
import "../globals.css";

import LeftSideBar from "@/components/layout/LeftSideBar";
import MainContainer from "@/components/layout/MainContainer";
import TopBar from "@/components/layout/TopBar";
import BottomBar from "@/components/layout/BottomBar";
import RightSideBar from "@/components/layout/RightSideBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang='en'>
        <body className={`${inter.className} bg-purple-2`}>
          <main className='flex flex-row'>
            <LeftSideBar />
            <MainContainer>{children}</MainContainer>
            <RightSideBar />
          </main>
          <BottomBar />
        </body>
      </html>
    </Provider>
  );
}
